[package]
name = "pinocchio-study"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
pinocchio = { version = "0.7.1", features = ["std"] }
pinocchio-pubkey = "0.2.2"
